name: 'Bump version and set tag'
description: 'Bump the version and sets the tag'
outputs:
  tag:
    description: 'Tag string'
    value: ${{ steps.set-tag.outputs.tag }}
runs:
  using: 'composite'
  steps: 
    - run: ./bumpversion.sh
      shell: bash
    - id: set-tag
      run: echo "::set-output name=tag::v$(cat VERSION)"
      shell: bash